apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
type: Opaque
data:
    POSTGRES_USER: dXNlcm5hbWU=
    POSTGRES_PASSWORD: cGFzc3dvcmQ=





# to generate username and password in base64url:
# in terminal: echo -n '{plaintext}' | base64
# username: username, password: password